package miniJava.SyntacticAnalyzer;

public enum TokenType {CLASS, IDENTIFIER, LBRACKET, RBRACKET, LBRACE, 
				   RBRACE, LPAREN, RPAREN, RETURN, SEMICOLON, 
				   PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, 
				   VOID, EOT, IF, ELSE, WHILE, PERIOD, 
				   NEW, THIS, COMMA, UNOP, BINOP, MINUS, 
				   NUM, EQUALS, TRUE, FALSE, ERROR, COMMENT}
